version: '3'

services:
  mysqlcontainer:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=spring_app_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuserpwd
    volumes:
      - /tmp/mysql_data:/var/lib/mysql
  scripservicecontainer:
    image: scripservice:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlcontainer:3306/spring_app_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=testuser
      - SPRING_DATASOURCE_PASSWORD=testuserpwd
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqlcontainer
    ports:
      - 8087:8080
    volumes:
      - /tmp:/usr/local/app/logs
